"""create devices table

Revision ID: 1331ea7cf501
Revises: 9cbb9d237d49
Create Date: 2026-06-11 08:03:28.259511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1331ea7cf501'
down_revision: Union[str, Sequence[str], None] = '9cbb9d237d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('mgmt_ip', sa.String(length=45), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credential_profiles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('mgmt_ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
